### ISSUE TITLE
can you share the datasets?

### ISSUE THREAD

**Issue by zlszhonglongshen** [ravishankar2463/Fake-Image-Detection#1]
can you share the datasets?  593956670@qq.com  thks!

**Comment by ravishankar2463** [comment]
The dataset I used can be found on this link :- [CASIA DATASET](https://www.kaggle.com/sophatvathana/casia-dataset)

**Comment by zlszhonglongshen** [comment]
> The dataset I used can be found on this link :- [CASIA DATASET](https://www.kaggle.com/sophatvathana/casia-dataset)

thks！
